# Generated by Django 4.2.16 on 2024-09-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramType',
            new_name='Tag',
        ),
    ]
