# Generated by Django 4.2.16 on 2024-10-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_in_program', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='program',
            old_name='body',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='program',
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('order_in_day', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.program'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coach.workout'),
            preserve_default=False,
        ),
    ]
