# Generated by Django 4.2.16 on 2024-10-04 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_user_coach_user_is_athlete_user_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='assigned_athletes',
            field=models.ManyToManyField(blank=True, related_name='assigned_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
