# Generated by Django 4.2.16 on 2024-10-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_remove_exercise_workout_block_alter_exercise_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='coach.workout'),
        ),
    ]
