# Generated by Django 4.2.16 on 2024-10-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_alter_block_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='coach.workout'),
            preserve_default=False,
        ),
    ]
