# Generated by Django 4.2.16 on 2024-10-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_alter_block_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='block',
        ),
    ]
