# Generated by Django 4.2.16 on 2024-10-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_remove_exercise_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coach.block'),
            preserve_default=False,
        ),
    ]
