# Generated by Django 4.2.16 on 2024-10-24 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_exercise_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_workouts', to='coach.workout')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps_completed', models.IntegerField()),
                ('weight_completed', models.IntegerField()),
                ('logged_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sets', to='coach.loggedworkout')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sets', to='coach.set')),
            ],
        ),
    ]
