# Generated by Django 4.2.16 on 2024-10-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_loggedworkout_loggedset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedworkout',
            old_name='date',
            new_name='date_logged',
        ),
    ]
