# Generated by Django 4.2.16 on 2024-10-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_rename_date_loggedworkout_date_logged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedworkout',
            old_name='date_logged',
            new_name='date',
        ),
    ]
