# Generated by Django 4.2.16 on 2024-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_alter_workout_day_alter_workout_order_in_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedset',
            name='reps_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loggedset',
            name='weight_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
