# Generated by Django 4.2.16 on 2024-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0019_alter_loggedset_reps_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='users', to='coach.exercisename'),
        ),
    ]
