# Generated by Django 4.2.16 on 2024-11-22 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0020_exercisename_user_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisename',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
