# Generated by Django 4.2.16 on 2024-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0021_exercisename_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loggedworkout',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
